"""Validation summary regenerated from artefacts, not from notebooks."""

from __future__ import annotations

import json
from pathlib import Path


def write_report(artifact_dir: Path) -> None:
    metrics = json.loads((artifact_dir / "metrics.json").read_text(encoding="utf-8"))
    lines = [
        "# Validation report",
        "",
        "This file is regenerated by `make reproduce`. It is not a paper.",
        "Call the system a digital shadow: data flows one way and nothing actuates the plant.",
        "",
        metrics.get("data_note", ""),
        "",
        "## RQ1 cooling time constant",
        "",
    ]
    for machine, payload in metrics.get("per_machine", {}).items():
        lines.append(
            f"- Machine {machine}: n={payload.get('n_tau')} median tau={payload.get('tau_median_min')} min "
            f"CV={payload.get('tau_cv')} UA={payload.get('ua_eff_w_per_k')} W/K"
        )
    lines += ["", "## RQ2 yield", ""]
    targets = metrics.get("yield", {}).get("targets", {})
    for name, block in targets.items():
        held = block.get("held_out")
        b2 = block.get("baseline_b2")
        lines.append(f"- {name}: held-out {held} baseline B2 {b2} n_note in each metric")
    lines += ["", f"Citations: {metrics.get('cp_charge_citation')}", ""]
    (artifact_dir / "validation.md").write_text("\n".join(lines), encoding="utf-8")
